
# init
add-pssnapin displaysettingscmdlets
get-pssnapin display*
echo _________________________________________________________________
help get-displaysettings
echo _________________________________________________________________
help set-displaysettings
echo _________________________________________________________________
