//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplaySettings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DisplaySettings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is no valid number..
        /// </summary>
        internal static string Err_ArgumentNoNumber {
            get {
                return ResourceManager.GetString("Err_ArgumentNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device #{0} not found..
        /// </summary>
        internal static string Err_DeviceNotFound {
            get {
                return ResourceManager.GetString("Err_DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments or switches provided..
        /// </summary>
        internal static string Err_NoArguments {
            get {
                return ResourceManager.GetString("Err_NoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching display setting found..
        /// </summary>
        internal static string Err_NoMatchingDisplaySettings {
            get {
                return ResourceManager.GetString("Err_NoMatchingDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting values: {0}.
        /// </summary>
        internal static string Err_SettingValues {
            get {
                return ResourceManager.GetString("Err_SettingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter.
        /// </summary>
        internal static string Msg_Adapter {
            get {
                return ResourceManager.GetString("Msg_Adapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Depth.
        /// </summary>
        internal static string Msg_ColorDepth {
            get {
                return ResourceManager.GetString("Msg_ColorDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits per pixel.
        /// </summary>
        internal static string Msg_ColorDepthUnit {
            get {
                return ResourceManager.GetString("Msg_ColorDepthUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (current).
        /// </summary>
        internal static string Msg_Current {
            get {
                return ResourceManager.GetString("Msg_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Adapters.
        /// </summary>
        internal static string Msg_Header_DisplayAdapters {
            get {
                return ResourceManager.GetString("Msg_Header_DisplayAdapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        internal static string Msg_Header_DisplaySettings {
            get {
                return ResourceManager.GetString("Msg_Header_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string Msg_Monitor {
            get {
                return ResourceManager.GetString("Msg_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Msg_Position {
            get {
                return ResourceManager.GetString("Msg_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (primary).
        /// </summary>
        internal static string Msg_Primary {
            get {
                return ResourceManager.GetString("Msg_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Rate.
        /// </summary>
        internal static string Msg_RefreshRate {
            get {
                return ResourceManager.GetString("Msg_RefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string Msg_Resolution {
            get {
                return ResourceManager.GetString("Msg_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting values returned successfully..
        /// </summary>
        internal static string OK_SettingValues {
            get {
                return ResourceManager.GetString("OK_SettingValues", resourceCulture);
            }
        }
    }
}
